### ISSUE TITLE
Why pre_enc decomposes seasonality and trend when channel_independence == 0

### ISSUE THREAD

**Issue by SweeRoty** [kwuking/TimeMixer#33] opened 2024-06-14 08:14 UTC
```
    def pre_enc(self, x_list):
        if self.channel_independence == 1:
            return (x_list, None)
        else:
            out1_list = []
            out2_list = []
            for x in x_list:
                x_1, x_2 = self.preprocess(x)
                out1_list.append(x_1)
                out2_list.append(x_2)
            return (out1_list, out2_list)
```
When channel_independence == 0, the following embedding layer only takes the seasonality part. What's the motivation? Thank you

**Comment by kwuking** [comment] 2024-06-14 12:52
Thank you for your interest in our work. By closing the channel independence here, extracting the seasonal and trend characteristics between different channels will affect each other. This is caused by the differences in data distribution between channels. Therefore, in this case, we first eliminate the interference of trends to allow the model to learn in a more pure form.

**Closed by kwuking** 2024-06-14 12:52 UTC
